FROM python:3.12-slim

ARG APP_USER=aryon
ENV APP_USER=${APP_USER}

RUN useradd --create-home --no-log-init --shell /bin/false ${APP_USER}

WORKDIR /app

ENV PORT=8000

USER ${APP_USER}

EXPOSE ${PORT}
